# Generated by Django 5.2.9 on 2025-12-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Indoor18MetersGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('items', models.ManyToManyField(related_name='grids', to='grid.griditem')),
            ],
            options={
                'verbose_name': 'Indoor 18 Meters Grid',
                'verbose_name_plural': 'Indoor 18 Meters Grids',
            },
        ),
    ]
