# Generated by Django 5.2.9 on 2025-12-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Grid_10x3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x3y2', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': '10x3 Grid',
                'verbose_name_plural': '10x3 Grids',
                'db_table': 'grid_10x3',
            },
        ),
        migrations.CreateModel(
            name='Grid_5x5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '5x5 Grid',
                'verbose_name_plural': '5x5 Grids',
                'db_table': 'grid_5x5',
            },
        ),
    ]
