# Generated by Django 5.2.9 on 2025-12-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indoor18metersgrid',
            name='items',
            field=models.ManyToManyField(to='grid.griditem'),
        ),
        migrations.CreateModel(
            name='Indoor25MetersGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('items', models.ManyToManyField(to='grid.griditem')),
            ],
            options={
                'verbose_name': 'Indoor 25 Meters Grid',
                'verbose_name_plural': 'Indoor 25 Meters Grids',
            },
        ),
    ]
