# Generated by Django 5.2.9 on 2025-12-10 12:35

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BowTypeMembership',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('bowtype__name', 'archer__last_name'))),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='bowtype information')),
            ],
            options={
                'verbose_name': 'Bow Type Membership',
                'verbose_name_plural': 'Bow Type Memberships',
                'db_table': 'bowtypemembership',
                'ordering': ['bowtype__name'],
            },
        ),
        migrations.CreateModel(
            name='BowType',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='format: required, max-32', max_length=32, unique=True, verbose_name='bow type name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='bowtype information')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='bowtype_author', to=settings.AUTH_USER_MODEL, verbose_name='author of bowtype')),
            ],
            options={
                'verbose_name': 'Bow Type',
                'verbose_name_plural': 'Bow Types',
                'db_table': 'bowtype',
                'ordering': ['name'],
            },
        ),
    ]
