# Generated by Django 5.2.9 on 2025-12-11 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archery_materials', '0001_initial'),
        ('modeling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bowtypemembership',
            name='archer',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='bowtypemembership_archer', to='modeling.archer', verbose_name='bowtypemembership archer'),
        ),
        migrations.AddField(
            model_name='bowtypemembership',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='bowtype_membership_author', to=settings.AUTH_USER_MODEL, verbose_name='author of bowtypemembership'),
        ),
        migrations.AddField(
            model_name='bowtypemembership',
            name='bowtype',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='BowTypeMembership', to='archery_materials.bowtype', verbose_name='bowtypemembership bowtype'),
        ),
        migrations.AddField(
            model_name='bowtype',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='bowtypes', through='archery_materials.BowTypeMembership', to='modeling.archer', verbose_name='archers in bowtype'),
        ),
    ]
