# Generated by Django 5.2.9 on 2025-12-05 10:26

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archery_materials', '0001_initial'),
        ('modeling', '0005_gridpage_alter_scoringsheet_rows_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowtype',
            name='info',
            field=models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='bowtype information'),
        ),
        migrations.CreateModel(
            name='BowTypeMembership',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('bowtype__name', 'archer__last_name'))),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='bowtype information')),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='bowtypemembership_archer', to='modeling.archer', verbose_name='bowtypemembership archer')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='bowtype_membership_author', to=settings.AUTH_USER_MODEL, verbose_name='author of bowtypemembership')),
                ('bowtype', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='BowTypeMembership', to='archery_materials.bowtype', verbose_name='bowtypemembership bowtype')),
            ],
            options={
                'verbose_name': 'Bow Type Membership',
                'verbose_name_plural': 'Bow Type Memberships',
                'db_table': 'bowtypemembership',
                'ordering': ['bowtype__name'],
            },
        ),
        migrations.AddField(
            model_name='bowtype',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='bowtypes', through='archery_materials.BowTypeMembership', to='modeling.archer', verbose_name='archers in bowtype'),
        ),
    ]
