# Generated by Django 5.2.9 on 2025-12-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archery_materials', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bowtypemembership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
