# Generated by Django 5.2.9 on 2025-12-16 15:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetitionMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GridPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='format: required, max-32', max_length=32, unique=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='Info')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='agegroup_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Age Group',
                'verbose_name_plural': 'Age Groups',
                'db_table': 'agegroups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Archer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='Last name')),
                ('first_name', models.CharField(help_text='format: required, max-32', max_length=32, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, help_text='format: not required, max-6', max_length=6, null=True, verbose_name='Middle name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='last_name')),
                ('union_number', models.PositiveIntegerField(help_text='format: not required', null=True, unique=True, verbose_name='Union number')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='Info')),
                ('email', models.EmailField(blank=True, help_text='format: not required, max-254', max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='format: not required, max-15', max_length=15, null=True, verbose_name='Phone number')),
                ('address', models.CharField(blank=True, help_text='format: not required, max-128', max_length=128, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, help_text='format: not required, max-64', max_length=64, null=True, verbose_name='City')),
                ('zip_code', models.CharField(blank=True, help_text='format: not required, max-6', max_length=6, null=True, verbose_name='Zip code')),
                ('province', models.CharField(blank=True, help_text='format: not required, max-64', max_length=64, null=True, verbose_name='Province')),
                ('birth_date', models.DateField(blank=True, help_text='format: Y-m-d, not required', null=True, verbose_name='Birth date')),
                ('author', models.ForeignKey(default=1, help_text='format: not required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='archer_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Archer',
                'verbose_name_plural': 'Archers',
                'db_table': 'archers',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='Info')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='category_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('category__name', 'archer__last_name'))),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='Info')),
                ('agegroup', models.ForeignKey(blank=True, help_text='format: required', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorymembership_agegroup', to='modeling.agegroup', verbose_name='Age Group')),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='categorymembership_archer', to='modeling.archer', verbose_name='Archer')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='category_membership_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='categorymemberships', to='modeling.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category Membership',
                'verbose_name_plural': 'Category Memberships',
                'db_table': 'categorymemberships',
                'ordering': ['category__name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='categories', through='modeling.CategoryMembership', to='modeling.archer', verbose_name='Archers'),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('address', models.CharField(blank=True, help_text='format: not required, max-128', max_length=128, null=True, verbose_name='Address')),
                ('zip_code', models.CharField(blank=True, help_text='format: not required, max-6', max_length=6, null=True, verbose_name='Zip code')),
                ('town', models.CharField(blank=True, help_text='format: not required, max-64', max_length=64, null=True, verbose_name='Town')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='Info')),
                ('email', models.EmailField(blank=True, help_text='format: not required, max-254', max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='format: not required, max-15', max_length=15, null=True, verbose_name='Phone number')),
                ('website', models.URLField(blank=True, help_text='format: not required, max-200', null=True, verbose_name='Website')),
                ('social_media', models.CharField(blank=True, help_text='format: not required, max-128', max_length=128, null=True, verbose_name='Social media')),
                ('author', models.ForeignKey(default=1, help_text='format: not required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='author_club', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'db_table': 'clubs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('archer__last_name', 'club__name'))),
                ('start_date', models.DateField(blank=True, help_text='format: Y-m-d, not required', null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, help_text='format: Y-m-d, not required', null=True, verbose_name='End date')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='Info')),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='clubmember_archer', to='modeling.archer', verbose_name='Archer')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='membership_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('club', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='modeling.club', verbose_name='Club')),
            ],
            options={
                'verbose_name': 'Club Membership',
                'verbose_name_plural': 'Club Memberships',
                'db_table': 'clubmemberships',
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='club',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='clubs', through='modeling.ClubMembership', to='modeling.archer', verbose_name='Archers'),
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(default='', help_text='format: required, max-64', max_length=64, unique=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('start_date', models.DateField(blank=True, help_text='format: Y-m-d, not required', null=True, verbose_name='Start date')),
                ('start_time', models.TimeField(blank=True, help_text='format: H:M:S, not required', null=True, verbose_name='Start time')),
                ('end_date', models.DateField(blank=True, help_text='format: Y-m-d, not required', null=True, verbose_name='End date')),
                ('end_time', models.TimeField(blank=True, help_text='format: H:M:S, not required', null=True, verbose_name='End time')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='Info')),
                ('author', models.ForeignKey(default=1, help_text='format: not required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='author_contest', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Contest',
                'verbose_name_plural': 'Contests',
                'db_table': 'contests',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContestMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('archer__last_name', 'contest__name'))),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='Info')),
                ('archer', models.ForeignKey(default=1, help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='archer_contest_membership', to='modeling.archer', verbose_name='Archer')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='author_contest_membership', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('contest', models.ForeignKey(default=1, help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='contest_membership', to='modeling.contest', verbose_name='Contest')),
            ],
            options={
                'verbose_name': 'Contest Membership',
                'verbose_name_plural': 'Contest Memberships',
                'db_table': 'contestmemberships',
                'ordering': ['contest__name'],
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='contest_archers', through='modeling.ContestMembership', to='modeling.archer', verbose_name='Archers'),
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='format: required, max-64', max_length=64, unique=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='Info')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='discipline_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
                'db_table': 'disciplines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('archer__last_name', 'discipline__name'))),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='Info')),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='archer_disciplinemembership', to='modeling.archer', verbose_name='Archer')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='discipline_membership_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('discipline', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='disciplinememberships', to='modeling.discipline', verbose_name='Discipline')),
            ],
            options={
                'verbose_name': 'Discipline Membership',
                'verbose_name_plural': 'Discipline Memberships',
                'db_table': 'disciplinememberships',
                'ordering': ['discipline__name'],
            },
        ),
        migrations.AddField(
            model_name='discipline',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='disciplines', through='modeling.DisciplineMembership', to='modeling.archer', verbose_name='Archers'),
        ),
        migrations.CreateModel(
            name='ScoringSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('columns', models.PositiveIntegerField(default=3, help_text='format: required min-3, max-20', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)], verbose_name='Columns')),
                ('rows', models.PositiveIntegerField(default=10, help_text='format: required min-3, max-20', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)], verbose_name='Rows')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='Info')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='scoringsheet_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Scoring Sheet',
                'verbose_name_plural': 'Scoring Sheets',
                'db_table': 'scoringsheets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TargetFace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(choices=[], help_text='format: required, max-64', max_length=64, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='Info')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='targetface_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Target Face',
                'verbose_name_plural': 'Target Faces',
                'db_table': 'targetfaces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TargetFaceNameChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='format: generated, max-128', max_length=128, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('environment', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], help_text='format: required, max-32', max_length=32, verbose_name='Environment')),
                ('discipline', models.CharField(choices=[('Target Archery', 'Target Archery'), ('Field Archery', 'Field Archery')], help_text='format: required, max-32', max_length=32, verbose_name='Discipline')),
                ('targetsize', models.CharField(choices=[('122 cm', '122 cm'), ('80 cm', '80 cm'), ('65 cm', '65 cm'), ('60 cm', '60 cm'), ('50 cm', '50 cm'), ('40 cm', '40 cm'), ('35 cm', '30 cm'), ('30 cm', '30 cm'), ('20 cm', '20 cm')], help_text='format: required, max-32', max_length=32, verbose_name='Target size')),
                ('keyfeature', models.CharField(choices=[('5-Zone', '5-Zone'), ('6-Zone', '6-Zone'), ('10-Zone', '10-Zone')], help_text='format: required, max-32', max_length=32, verbose_name='Key feature')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='Info')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='targetface_namechoice_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Target Face Name Choice',
                'verbose_name_plural': 'Target Faces Name Choices',
                'db_table': 'targetfacenamechoices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='Info')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='team_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('team__name', 'archer__last_name'))),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='Info')),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='teammembership_archer', to='modeling.archer', verbose_name='Archer')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='teammembership', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('team', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='teammemberships', to='modeling.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Team Membership',
                'verbose_name_plural': 'Team Memberships',
                'db_table': 'teammemberships',
                'ordering': ['team__name'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='teams', through='modeling.TeamMembership', to='modeling.archer', verbose_name='Archers'),
        ),
    ]
