# Generated by Django 5.2.9 on 2025-12-14 20:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetitionMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContestMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GridPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TargetFace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(choices=[], default='name of targetface', help_text='format: required, max-64', max_length=64, verbose_name='targetface name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='targetface information')),
            ],
            options={
                'verbose_name': 'Target Face',
                'verbose_name_plural': 'Target Faces',
                'db_table': 'targetfaces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='format: required, max-32', max_length=32, unique=True, verbose_name='age group name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='agegroup information')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='agegroup_author', to=settings.AUTH_USER_MODEL, verbose_name='author of agegroup')),
            ],
            options={
                'verbose_name': 'Age Group',
                'verbose_name_plural': 'Age Groups',
                'db_table': 'agegroups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Archer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='last name of archer')),
                ('first_name', models.CharField(help_text='format: required, max-32', max_length=32, verbose_name='first name of archer')),
                ('middle_name', models.CharField(blank=True, help_text='format: not required, max-6', max_length=6, null=True, verbose_name='middle name of archer')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='last_name')),
                ('union_number', models.PositiveIntegerField(help_text='format: not required', null=True, unique=True, verbose_name='union number of archer')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='info of archer')),
                ('email', models.EmailField(blank=True, help_text='format: not required, max-254', max_length=254, null=True, verbose_name='email address of archer')),
                ('phone', models.CharField(blank=True, help_text='format: not required, max-15', max_length=15, null=True, verbose_name='phone number of archer')),
                ('address', models.CharField(blank=True, help_text='format: not required, max-128', max_length=128, null=True, verbose_name='address of archer')),
                ('city', models.CharField(blank=True, help_text='format: not required, max-64', max_length=64, null=True, verbose_name='city of archer')),
                ('zip_code', models.CharField(blank=True, help_text='format: not required, max-6', max_length=6, null=True, verbose_name='zip code of archer')),
                ('province', models.CharField(blank=True, help_text='format: not required, max-64', max_length=64, null=True, verbose_name='province or state of archer')),
                ('birth_date', models.DateField(blank=True, help_text='format: Y-m-d, not required', null=True, verbose_name='birth date of archer')),
                ('author', models.ForeignKey(default=1, help_text='format: not required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='archer_author', to=settings.AUTH_USER_MODEL, verbose_name='author of archer')),
            ],
            options={
                'verbose_name': 'Archer',
                'verbose_name_plural': 'Archers',
                'db_table': 'archers',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='category name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='category information')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='category_author', to=settings.AUTH_USER_MODEL, verbose_name='author of category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('category__name', 'archer__last_name'))),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='category information')),
                ('agegroup', models.ForeignKey(blank=True, help_text='format: required', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorymembership_agegroup', to='modeling.agegroup', verbose_name='age group of category membership')),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='categorymembership_archer', to='modeling.archer', verbose_name='categorymembership archer')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='category_membership_author', to=settings.AUTH_USER_MODEL, verbose_name='author of categorymembership')),
                ('category', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='categorymemberships', to='modeling.category', verbose_name='categorymembership category')),
            ],
            options={
                'verbose_name': 'Category Membership',
                'verbose_name_plural': 'Category Memberships',
                'db_table': 'categorymemberships',
                'ordering': ['category__name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='categories', through='modeling.CategoryMembership', to='modeling.archer', verbose_name='archers in category'),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='club name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('address', models.CharField(blank=True, help_text='format: not required, max-128', max_length=128, null=True, verbose_name='address of club')),
                ('zip_code', models.CharField(blank=True, help_text='format: not required, max-6', max_length=6, null=True, verbose_name='zip code of archer')),
                ('town', models.CharField(blank=True, help_text='format: not required, max-64', max_length=64, null=True, verbose_name='town name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='club information')),
                ('email', models.EmailField(blank=True, help_text='format: not required, max-254', max_length=254, null=True, verbose_name='email address of club')),
                ('phone', models.CharField(blank=True, help_text='format: not required, max-15', max_length=15, null=True, verbose_name='phone number of club')),
                ('website', models.URLField(blank=True, help_text='format: not required, max-200', null=True, verbose_name='website of club')),
                ('social_media', models.CharField(blank=True, help_text='format: not required, max-128', max_length=128, null=True, verbose_name='social media handle of club')),
                ('author', models.ForeignKey(default=1, help_text='format: not required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='author_club', to=settings.AUTH_USER_MODEL, verbose_name='author of club')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'db_table': 'clubs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('archer__last_name', 'club__name'))),
                ('start_date', models.DateField(blank=True, help_text='format: Y-m-d, not required', null=True, verbose_name='start date of membership')),
                ('end_date', models.DateField(blank=True, help_text='format: Y-m-d, not required', null=True, verbose_name='end date of membership')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='membership information')),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='clubmember_archer', to='modeling.archer', verbose_name='archer who is member')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='membership_author', to=settings.AUTH_USER_MODEL, verbose_name='author of membership')),
                ('club', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='modeling.club', verbose_name='club of the member')),
            ],
            options={
                'verbose_name': 'Club Membership',
                'verbose_name_plural': 'Club Memberships',
                'db_table': 'clubmemberships',
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='club',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='clubs', through='modeling.ClubMembership', to='modeling.archer', verbose_name='archers in club'),
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='format: required, max-64', max_length=64, unique=True, verbose_name='name of discipline')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='information of discipline')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='discipline_author', to=settings.AUTH_USER_MODEL, verbose_name='author of discipline')),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
                'db_table': 'disciplines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('archer__last_name', 'discipline__name'))),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='info of disciplinemembership')),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='archer_disciplinemembership', to='modeling.archer', verbose_name='archer of disciplinemembership')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='discipline_membership_author', to=settings.AUTH_USER_MODEL, verbose_name='author of membership')),
                ('discipline', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='disciplinememberships', to='modeling.discipline', verbose_name='discipline of disciplinemembership')),
            ],
            options={
                'verbose_name': 'Discipline Membership',
                'verbose_name_plural': 'Discipline Memberships',
                'db_table': 'disciplinememberships',
                'ordering': ['discipline__name'],
            },
        ),
        migrations.AddField(
            model_name='discipline',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='disciplines', through='modeling.DisciplineMembership', to='modeling.archer', verbose_name='archers of discipline'),
        ),
        migrations.CreateModel(
            name='ScoringSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='scoringsheet name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('columns', models.PositiveIntegerField(default=3, help_text='format: required min-3, max-20', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)], verbose_name='number of columns')),
                ('rows', models.PositiveIntegerField(default=10, help_text='format: required min-3, max-20', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)], verbose_name='number of rows')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='scoringsheet information')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='scoringsheet_author', to=settings.AUTH_USER_MODEL, verbose_name='author of scoring sheet')),
            ],
            options={
                'verbose_name': 'Scoring Sheet',
                'verbose_name_plural': 'Scoring Sheets',
                'db_table': 'scoringsheets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TargetFaceNameChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='format: required, max-128', max_length=128, unique=True, verbose_name='name of TargetFaceNameChoice')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('environment', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], help_text='format: required, max-32', max_length=32, unique=True, verbose_name='environment of TargetFaceNameChoice')),
                ('discipline', models.CharField(choices=[('122', '122'), ('80', '80'), ('60', '60'), ('40', '40'), ('30', '30'), ('20', '20')], help_text='format: required, max-32', max_length=32, unique=True, verbose_name='discipline of TargetFaceNameChoice')),
                ('targetsize', models.CharField(choices=[('Target Archery', 'Target Archery'), ('Field Archery', 'Field Archery'), ('3D Archery', '3D Archery')], help_text='format: required, max-32', max_length=32, unique=True, verbose_name='targetsize of TargetFaceNameChoice')),
                ('keyfeature', models.CharField(choices=[('5-Zone', '5-Zone'), ('10-Zone', '10-Zone'), ('3D', '3D')], help_text='format: required, max-32', max_length=32, unique=True, verbose_name='keyfeature of TargetFaceNameChoice')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='info of TargetFaceNameChoice')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='targetface_namechoice_author', to=settings.AUTH_USER_MODEL, verbose_name='author of TargetFaceNameChoice')),
            ],
            options={
                'verbose_name': 'Target Face Name Choice',
                'verbose_name_plural': 'Target Faces Name Choices',
                'db_table': 'targetfacenamechoices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='team name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='team information')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='team_author', to=settings.AUTH_USER_MODEL, verbose_name='author of team')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('team__name', 'archer__last_name'))),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='teammembership information')),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='teammembership_archer', to='modeling.archer', verbose_name='teammembership archer')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='teammembership', to=settings.AUTH_USER_MODEL, verbose_name='author of teammembership')),
                ('team', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='teammemberships', to='modeling.team', verbose_name='teammembership team')),
            ],
            options={
                'verbose_name': 'Team Membership',
                'verbose_name_plural': 'Team Memberships',
                'db_table': 'teammemberships',
                'ordering': ['team__name'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='teams', through='modeling.TeamMembership', to='modeling.archer', verbose_name='archers in team'),
        ),
    ]
