# Generated by Django 5.2.8 on 2025-12-01 11:51

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archer',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='last name of archer')),
                ('first_name', models.CharField(help_text='format: required, max-32', max_length=32, verbose_name='first name of archer')),
                ('middle_name', models.CharField(blank=True, help_text='format: not required, max-6', max_length=6, null=True, verbose_name='middle name of archer')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='last_name')),
                ('union_number', models.PositiveIntegerField(blank=True, help_text='format: not required', null=True, unique=True, verbose_name='union number of archer')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='archer information')),
                ('email', models.EmailField(blank=True, help_text='format: not required, max-254', max_length=254, null=True, verbose_name='email address of archer')),
                ('phone', models.CharField(blank=True, help_text='format: not required, max-15', max_length=15, null=True, verbose_name='phone number of archer')),
                ('address', models.CharField(blank=True, help_text='format: not required, max-128', max_length=128, null=True, verbose_name='address of archer')),
                ('city', models.CharField(blank=True, help_text='format: not required, max-64', max_length=64, null=True, verbose_name='city of archer')),
                ('province', models.CharField(blank=True, help_text='format: not required, max-64', max_length=64, null=True, verbose_name='state or province of archer')),
                ('zip_code', models.CharField(blank=True, help_text='format: not required, max-6', max_length=6, null=True, verbose_name='zip code of archer')),
                ('birth_date', models.DateField(blank=True, help_text='format: Y-m-d, not required', null=True, verbose_name='birth date of archer')),
                ('author', models.ForeignKey(default=1, help_text='format: not required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='archer_author', to=settings.AUTH_USER_MODEL, verbose_name='author of archer')),
            ],
            options={
                'verbose_name': 'Archer',
                'verbose_name_plural': 'Archers',
                'db_table': 'archer',
                'ordering': ['last_name'],
            },
        ),
    ]
