# Generated by Django 5.2.9 on 2025-12-22 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modeling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroup',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='agegroup_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='archer',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: not required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='archer_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='category',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='category_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='categorymembership',
            name='agegroup',
            field=models.ForeignKey(blank=True, help_text='format: required', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorymembership_agegroup', to='modeling.agegroup', verbose_name='Age Group'),
        ),
        migrations.AddField(
            model_name='categorymembership',
            name='archer',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='categorymembership_archer', to='modeling.archer', verbose_name='Archer'),
        ),
        migrations.AddField(
            model_name='categorymembership',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='category_membership_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='categorymembership',
            name='category',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='categorymemberships', to='modeling.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='categories', through='modeling.CategoryMembership', to='modeling.archer', verbose_name='Archers'),
        ),
        migrations.AddField(
            model_name='club',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: not required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='author_club', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='archer',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='clubmember_archer', to='modeling.archer', verbose_name='Archer'),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='membership_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='club',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='modeling.club', verbose_name='Club'),
        ),
        migrations.AddField(
            model_name='club',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='clubs', through='modeling.ClubMembership', to='modeling.archer', verbose_name='Archers'),
        ),
        migrations.AddField(
            model_name='competition',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: not required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='author_competition', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='competitionmembership',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='competition_membership_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='competitionmembership',
            name='competition',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='competitionmembership_competition', to='modeling.competition', verbose_name='Competition'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='discipline_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='disciplinemembership',
            name='archer',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='archer_disciplinemembership', to='modeling.archer', verbose_name='Archer'),
        ),
        migrations.AddField(
            model_name='disciplinemembership',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='discipline_membership_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='disciplinemembership',
            name='discipline',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='disciplinememberships', to='modeling.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='disciplines', through='modeling.DisciplineMembership', to='modeling.archer', verbose_name='Archers'),
        ),
        migrations.AddField(
            model_name='round',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: not required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='author_round', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='competitionmembership',
            name='round',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='competitionmembership_round', to='modeling.round', verbose_name='Round'),
        ),
        migrations.AddField(
            model_name='competition',
            name='rounds',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='competitions', through='modeling.CompetitionMembership', to='modeling.round', verbose_name='Competitions'),
        ),
        migrations.AddField(
            model_name='roundmembership',
            name='archer',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='archer_round_membership', to='modeling.archer', verbose_name='Archer'),
        ),
        migrations.AddField(
            model_name='roundmembership',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='author_round_membership', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='roundmembership',
            name='round',
            field=models.ForeignKey(default=1, help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='round_membership', to='modeling.round', verbose_name='Round'),
        ),
        migrations.AddField(
            model_name='round',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='round_archers', through='modeling.RoundMembership', to='modeling.archer', verbose_name='Archers'),
        ),
        migrations.AddField(
            model_name='score',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='score_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='score',
            name='round_archer',
            field=models.ForeignKey(blank=True, help_text='format: required', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='score_round_archer', to='modeling.roundmembership', verbose_name='Round & Archer,'),
        ),
        migrations.AddField(
            model_name='scoringsheet',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='scoringsheet_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='targetface',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='targetface_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='targetfacenamechoice',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='targetface_namechoice_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='team',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='team_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='archer',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='teammembership_archer', to='modeling.archer', verbose_name='Archer'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='teammembership', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='teammembership_team', to='modeling.team', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='teams', through='modeling.TeamMembership', to='modeling.archer', verbose_name='Archers'),
        ),
    ]
