# Generated by Django 5.2.9 on 2025-12-17 14:09

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundmembership',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('archer__last_name', 'round__name')),
        ),
        migrations.AlterModelTable(
            name='round',
            table='rounds',
        ),
    ]
