# Generated by Django 5.2.8 on 2025-12-01 12:47

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='club name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('address', models.CharField(blank=True, help_text='format: not required, max-128', max_length=128, null=True, verbose_name='address of club')),
                ('town', models.CharField(blank=True, help_text='format: not required, max-64', max_length=64, null=True, verbose_name='town name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='club information')),
                ('email', models.EmailField(blank=True, help_text='format: not required, max-254', max_length=254, null=True, verbose_name='email address of club')),
                ('phone', models.CharField(blank=True, help_text='format: not required, max-15', max_length=15, null=True, verbose_name='phone number of club')),
                ('website', models.URLField(blank=True, help_text='format: not required, max-200', null=True, verbose_name='website of club')),
                ('social_media', models.CharField(blank=True, help_text='format: not required, max-128', max_length=128, null=True, verbose_name='social media handle of club')),
                ('author', models.ForeignKey(default=1, help_text='format: not required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='author_club', to=settings.AUTH_USER_MODEL, verbose_name='author of club')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'db_table': 'club',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, help_text='format: Y-m-d, not required', null=True, verbose_name='start date of membership')),
                ('end_date', models.DateField(blank=True, help_text='format: Y-m-d, not required', null=True, verbose_name='end date of membership')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='membership information')),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='clubmember_archer', to='modeling.archer', verbose_name='archer who is member')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='membership_author', to=settings.AUTH_USER_MODEL, verbose_name='author of membership')),
                ('club', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='modeling.club', verbose_name='club of the member')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'db_table': 'membership',
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='club',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='clubs', through='modeling.ClubMembership', to='modeling.archer', verbose_name='archers in club'),
        ),
    ]
