# Generated by Django 5.2.9 on 2025-12-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetface',
            name='name',
            field=models.CharField(help_text='format: required, max-64', max_length=64, unique=True, verbose_name='Name'),
        ),
    ]
