# Generated by Django 5.2.9 on 2025-12-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetfacenamechoice',
            name='discipline',
            field=models.CharField(choices=[('Target Archery', 'Target Archery'), ('Field Archery', 'Field Archery'), ('3D Archery', '3D Archery')], help_text='format: required, max-32', max_length=32, unique=True, verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='targetfacenamechoice',
            name='environment',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], help_text='format: required, max-32', max_length=32, unique=True, verbose_name='Environment'),
        ),
        migrations.AlterField(
            model_name='targetfacenamechoice',
            name='keyfeature',
            field=models.CharField(choices=[('5-Zone', '5-Zone'), ('10-Zone', '10-Zone'), ('3D', '3D')], help_text='format: required, max-32', max_length=32, unique=True, verbose_name='Key feature'),
        ),
        migrations.AlterField(
            model_name='targetfacenamechoice',
            name='name',
            field=models.CharField(help_text='format: required, max-128', max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='targetfacenamechoice',
            name='targetsize',
            field=models.CharField(choices=[('122', '122'), ('80', '80'), ('60', '60'), ('40', '40'), ('30', '30'), ('20', '20')], help_text='format: required, max-32', max_length=32, unique=True, verbose_name='Target size'),
        ),
    ]
