# Generated by Django 5.2.8 on 2025-12-03 11:57

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringSheet',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='format: not required, max-64', max_length=64, verbose_name='scoringsheet name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='scoringsheet information')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='scoringsheet_author', to=settings.AUTH_USER_MODEL, verbose_name='author of scoring sheet')),
            ],
            options={
                'verbose_name': 'Scoring Sheet',
                'verbose_name_plural': 'Scoring Sheets',
                'db_table': 'scoringsheet',
                'ordering': ['name'],
            },
        ),
    ]
