# Generated by Django 5.2.8 on 2025-12-03 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0002_scoringsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringsheet',
            name='columns',
            field=models.PositiveIntegerField(default=3, help_text='format: required min-3, max-20', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)], verbose_name='number of columns'),
        ),
        migrations.AddField(
            model_name='scoringsheet',
            name='rows',
            field=models.PositiveIntegerField(default=20, help_text='format: required min-3, max-20', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)], verbose_name='number of rows'),
        ),
    ]
