# Generated by Django 5.2.9 on 2025-12-10 14:01

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0002_score_scoremembership_delete_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetDiameter',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
