# Generated by Django 5.2.8 on 2025-12-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0002_club_clubmembership_club_archers'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='zip_code',
            field=models.CharField(blank=True, help_text='format: not required, max-6', max_length=6, null=True, verbose_name='zip code of archer'),
        ),
    ]
