# Generated by Django 5.2.9 on 2025-12-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0002_alter_targetface_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetfacenamechoice',
            name='name',
            field=models.CharField(help_text='format: generated, max-128', max_length=128, unique=True, verbose_name='Name'),
        ),
    ]
