# Generated by Django 5.2.9 on 2025-12-17 15:32

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0002_alter_roundmembership_slug_alter_round_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Score', 'verbose_name_plural': 'Scores'},
        ),
        migrations.AddField(
            model_name='score',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='score_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='score',
            name='info',
            field=models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='Info'),
        ),
        migrations.AddField(
            model_name='score',
            name='number_of_arrows',
            field=models.PositiveIntegerField(default=0, help_text='format: not required', verbose_name='Number of arrows'),
        ),
        migrations.AddField(
            model_name='score',
            name='round_archer',
            field=models.ForeignKey(blank=True, help_text='format: required', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='score_round_archer', to='modeling.roundmembership', verbose_name='Round & Archer,'),
        ),
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.PositiveIntegerField(blank=True, help_text='format: not required', null=True, verbose_name='Score'),
        ),
        migrations.AddField(
            model_name='score',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('round_archer__round__name', 'round_archer__archer__last_name')),
        ),
        migrations.AlterModelTable(
            name='score',
            table='scores',
        ),
    ]
