# Generated by Django 5.2.9 on 2025-12-04 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0003_scoringsheet_columns_scoringsheet_rows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='teammembership', to=settings.AUTH_USER_MODEL, verbose_name='author of teammembershipmembership'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='info',
            field=models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='teammembership information'),
        ),
    ]
