# Generated by Django 5.2.9 on 2025-12-11 07:35

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0003_targetdiameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinemembership',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('archer__last_name', 'discipline__name')),
        ),
    ]
