# Generated by Django 5.2.8 on 2025-12-02 07:18

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0003_club_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembership',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='club__name, archer__name'),
        ),
    ]
