# Generated by Django 5.2.9 on 2025-12-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0003_alter_targetfacenamechoice_discipline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetfacenamechoice',
            name='discipline',
            field=models.CharField(choices=[('Target Archery', 'Target Archery'), ('Field Archery', 'Field Archery')], help_text='format: required, max-32', max_length=32, verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='targetfacenamechoice',
            name='environment',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], help_text='format: required, max-32', max_length=32, verbose_name='Environment'),
        ),
        migrations.AlterField(
            model_name='targetfacenamechoice',
            name='keyfeature',
            field=models.CharField(choices=[('5-Zone', '5-Zone'), ('6-Zone', '6-Zone'), ('10-Zone', '10-Zone')], help_text='format: required, max-32', max_length=32, verbose_name='Key feature'),
        ),
        migrations.AlterField(
            model_name='targetfacenamechoice',
            name='name',
            field=models.CharField(help_text='format: generated, max-128', max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='targetfacenamechoice',
            name='targetsize',
            field=models.CharField(choices=[('122 cm', '122 cm'), ('80 cm', '80 cm'), ('65 cm', '65 cm'), ('60 cm', '60 cm'), ('50 cm', '50 cm'), ('40 cm', '40 cm'), ('35 cm', '30 cm'), ('30 cm', '30 cm'), ('20 cm', '20 cm')], help_text='format: required, max-32', max_length=32, verbose_name='Target size'),
        ),
    ]
