# Generated by Django 5.2.9 on 2025-12-15 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0004_alter_targetfacenamechoice_discipline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='targetface',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='targetface_author', to=settings.AUTH_USER_MODEL, verbose_name='author of TargetFace'),
        ),
        migrations.AlterField(
            model_name='targetface',
            name='name',
            field=models.CharField(default='name of targetface', help_text='format: required, max-64', max_length=64, verbose_name='targetface name'),
        ),
    ]
