# Generated by Django 5.2.9 on 2025-12-05 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0005_gridpage_alter_scoringsheet_rows_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymembership',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='category_membership_author', to=settings.AUTH_USER_MODEL, verbose_name='author of categorymembership'),
        ),
    ]
