# Generated by Django 5.2.8 on 2025-12-02 13:33

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0005_alter_clubmembership_slug_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymembership',
            options={'ordering': ['category__name'], 'verbose_name': 'Category Membership', 'verbose_name_plural': 'Category Memberships'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='age_group',
        ),
        migrations.AddField(
            model_name='categorymembership',
            name='age_group',
            field=models.CharField(blank=True, choices=[('youth', 'Youth'), ('junior', 'Junior'), ('senior', 'Senior'), ('master', 'Master'), ('veteran', 'Veteran'), ('other', 'Other')], help_text='format: not required, max-32', max_length=32, null=True, verbose_name='age group of category membership'),
        ),
        migrations.AddField(
            model_name='categorymembership',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='category_membership_author', to=settings.AUTH_USER_MODEL, verbose_name='author of category membership'),
        ),
        migrations.AddField(
            model_name='categorymembership',
            name='info',
            field=models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='category information'),
        ),
        migrations.AlterField(
            model_name='categorymembership',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('category__name', 'archer__last_name')),
        ),
        migrations.AlterModelTable(
            name='categorymembership',
            table='categorymembership',
        ),
        migrations.AlterModelTable(
            name='clubmembership',
            table='clubmembership',
        ),
    ]
