# Generated by Django 5.2.9 on 2025-12-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0006_alter_targetface_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetface',
            name='name',
            field=models.CharField(choices=[], help_text='format: required, max-64', max_length=64, verbose_name='targetface name'),
        ),
    ]
