# Generated by Django 5.2.9 on 2025-12-07 20:48

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0007_competition_competitionmembership_contest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='format: required, max-64', max_length=64, unique=True, verbose_name='discipline name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='discipline information')),
                ('author', models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='discipline_author', to=settings.AUTH_USER_MODEL, verbose_name='author of discipline')),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
                'db_table': 'discipline',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineMembership',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='disciplinemembership_archer', to='modeling.archer', verbose_name='disciplinemembership archer')),
                ('discipline', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='disciplinememberships', to='modeling.discipline', verbose_name='disciplinemembership discipline')),
            ],
            options={
                'verbose_name': 'Discipline Membership',
                'verbose_name_plural': 'Discipline Memberships',
                'db_table': 'disciplinemembership',
                'ordering': ['discipline__name'],
            },
        ),
        migrations.AddField(
            model_name='discipline',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='disciplines', through='modeling.DisciplineMembership', to='modeling.archer', verbose_name='archers in discipline'),
        ),
    ]
